version: '3.8'

services:
  otp-bot:
    build: .
    container_name: otp-forwarder-bot
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./bot_data.db:/app/bot_data.db
    restart: unless-stopped
    environment:
      - HEADLESS=true
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('bot_data.db')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a monitoring service
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/etc/prometheus/console_libraries'
  #     - '--web.console.templates=/etc/prometheus/consoles'
